"""empty message

Revision ID: 00939fb12edb
Revises: 4a92ff4bf574
Create Date: 2021-02-26 10:34:21.323716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00939fb12edb'
down_revision = '4a92ff4bf574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('option_menu_id_fkey', 'option', type_='foreignkey')
    op.drop_column('option', 'extra_price')
    op.drop_column('option', 'new_one')
    op.drop_column('option', 'option_name')
    op.drop_column('option', 'menu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('option', sa.Column('option_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('option', sa.Column('new_one', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('option', sa.Column('extra_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('option_menu_id_fkey', 'option', 'menus', ['menu_id'], ['id'])
    op.drop_column('option', 'id')
    # ### end Alembic commands ###
