"""empty message

Revision ID: 0e608bee8ef2
Revises: 8fd4c7bdbd88
Create Date: 2021-02-21 10:57:24.181446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e608bee8ef2'
down_revision = '8fd4c7bdbd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('sale_status', sa.Boolean(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus_detail')
    op.drop_table('menus')
    # ### end Alembic commands ###
