"""empty message

Revision ID: 11090f350c03
Revises: 3fe6103ee496
Create Date: 2021-02-25 15:49:05.532642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11090f350c03'
down_revision = '3fe6103ee496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_data', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.drop_constraint('order_data_menus_id_fkey', 'order_data', type_='foreignkey')
    op.create_foreign_key(None, 'order_data', 'menus', ['menu_id'], ['id'])
    op.drop_column('order_data', 'menus_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_data', sa.Column('menus_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order_data', type_='foreignkey')
    op.create_foreign_key('order_data_menus_id_fkey', 'order_data', 'menus', ['menus_id'], ['id'])
    op.drop_column('order_data', 'menu_id')
    # ### end Alembic commands ###
