"""empty message

Revision ID: 11eb357422d4
Revises: c2694928df9c
Create Date: 2021-02-26 11:37:38.168735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eb357422d4'
down_revision = 'c2694928df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('store_id', sa.Integer(), nullable=True))
    op.drop_constraint('option_menu_id_fkey', 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'store', ['store_id'], ['id'])
    op.drop_column('option', 'menu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key('option_menu_id_fkey', 'option', 'menus', ['menu_id'], ['id'])
    op.drop_column('option', 'store_id')
    # ### end Alembic commands ###
