"""empty message

Revision ID: 17b734f6d403
Revises: 50895de4d4a8
Create Date: 2021-02-26 10:23:24.742675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b734f6d403'
down_revision = '50895de4d4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_id_key', 'option', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('option_id_key', 'option', ['id'])
    # ### end Alembic commands ###
