"""empty message

Revision ID: 1be5f2a16a7f
Revises: 5eff2dfe149e
Create Date: 2021-02-26 17:45:20.518112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1be5f2a16a7f'
down_revision = '5eff2dfe149e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'main_order', ['uuid'])
    op.drop_column('main_order', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'main_order', type_='unique')
    op.drop_column('main_order', 'uuid')
    # ### end Alembic commands ###
