"""empty message

Revision ID: 1c7a7924bfe6
Revises: 8107ff632909
Create Date: 2021-02-23 09:49:53.644360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7a7924bfe6'
down_revision = '8107ff632909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('create_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'create_at')
    # ### end Alembic commands ###
