"""empty message

Revision ID: 205543c37c21
Revises: 57146eb10d42
Create Date: 2021-02-24 17:42:24.048492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205543c37c21'
down_revision = '57146eb10d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('profile_im', sa.String(), nullable=True))
    op.drop_column('menus', 'profile_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('profile_img', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menus', 'profile_im')
    # ### end Alembic commands ###
