"""empty message

Revision ID: 2bf1c04c8897
Revises: eeac80bfa2b6
Create Date: 2021-02-26 12:12:34.971650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bf1c04c8897'
down_revision = 'eeac80bfa2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('menus', postgresql.ARRAY(sa.Integer(), dimensions=2), nullable=True))
    op.drop_constraint('cart_menu_id_fkey', 'cart', type_='foreignkey')
    op.drop_constraint('cart_option_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'quantity')
    op.drop_column('cart', 'option_id')
    op.drop_column('cart', 'menu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_option_id_fkey', 'cart', 'option', ['option_id'], ['id'])
    op.create_foreign_key('cart_menu_id_fkey', 'cart', 'menus', ['menu_id'], ['id'])
    op.drop_column('cart', 'menus')
    # ### end Alembic commands ###
