"""empty message

Revision ID: 2d8c19e30e89
Revises: d082ab4969d0
Create Date: 2021-02-21 00:12:09.060824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8c19e30e89'
down_revision = 'd082ab4969d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('comment', sa.String(length=300), nullable=False))
    op.drop_column('board', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('content', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('board', 'comment')
    # ### end Alembic commands ###
