"""empty message

Revision ID: 2f758bb577f5
Revises: a7787bfcc4a4
Create Date: 2021-02-25 17:09:02.661365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f758bb577f5'
down_revision = 'a7787bfcc4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('test_id', sa.Enum('1', '2', '3', name='myenum'), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'test_id')
    # ### end Alembic commands ###
