"""empty message

Revision ID: 44e204347672
Revises: ce0b2a352114
Create Date: 2021-02-22 16:51:43.104058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e204347672'
down_revision = 'ce0b2a352114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus_detail', sa.Column('profile', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus_detail', 'profile')
    # ### end Alembic commands ###
