"""empty message

Revision ID: 48dd0ece0bbe
Revises: 75bf8f4224a9
Create Date: 2021-03-02 14:38:05.739960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dd0ece0bbe'
down_revision = '75bf8f4224a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board', ['uuid'])
    op.create_unique_constraint(None, 'category', ['uuid'])
    op.create_unique_constraint(None, 'comment', ['uuid'])
    op.create_unique_constraint(None, 'main_order', ['uuid'])
    op.create_unique_constraint(None, 'menus', ['uuid'])
    op.create_unique_constraint(None, 'option', ['uuid'])
    op.create_unique_constraint(None, 'order_detail', ['uuid'])
    op.create_unique_constraint(None, 'refresh', ['uuid'])
    op.create_unique_constraint(None, 'store', ['uuid'])
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_constraint(None, 'refresh', type_='unique')
    op.drop_constraint(None, 'order_detail', type_='unique')
    op.drop_constraint(None, 'option', type_='unique')
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'main_order', type_='unique')
    op.drop_constraint(None, 'comment', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'board', type_='unique')
    # ### end Alembic commands ###
