"""empty message

Revision ID: 4a92ff4bf574
Revises: 34763bf6c175
Create Date: 2021-02-26 10:33:29.010696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a92ff4bf574'
down_revision = '34763bf6c175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('new_one', sa.Integer(), nullable=False))
    op.drop_column('option', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_column('option', 'new_one')
    # ### end Alembic commands ###
