"""empty message

Revision ID: 50895de4d4a8
Revises: 60ef1d232545
Create Date: 2021-02-25 17:59:40.245827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50895de4d4a8'
down_revision = '60ef1d232545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('extra_price', sa.Integer(), nullable=True))
    op.add_column('option', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.add_column('option', sa.Column('option_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'option', 'menus', ['menu_id'], ['id'])
    op.drop_column('option', 'hot_or_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('hot_or_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_column('option', 'option_name')
    op.drop_column('option', 'menu_id')
    op.drop_column('option', 'extra_price')
    # ### end Alembic commands ###
