"""empty message

Revision ID: 509a4baea51b
Revises: d053af454bc7
Create Date: 2021-02-21 12:25:02.539369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509a4baea51b'
down_revision = 'd053af454bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
