"""empty message

Revision ID: 515ad4f655c3
Revises: 31f911fd03ae
Create Date: 2021-02-24 15:20:28.689346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515ad4f655c3'
down_revision = '31f911fd03ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_like',
    sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name='board_like_board_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='board_like_users_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', name='board_like_pkey')
    )
    # ### end Alembic commands ###
