"""empty message

Revision ID: 52f92adbe268
Revises: 0356ef42673e
Create Date: 2021-03-02 10:27:03.000719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52f92adbe268'
down_revision = '0356ef42673e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'order_detail', ['uuid'])
    op.drop_column('order_detail', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'order_detail', type_='unique')
    op.drop_column('order_detail', 'uuid')
    # ### end Alembic commands ###
