"""empty message

Revision ID: 56133b78d9e9
Revises: 73fc8ba01074
Create Date: 2021-02-22 14:11:07.770534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56133b78d9e9'
down_revision = '73fc8ba01074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_like', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'board_like', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_like', type_='foreignkey')
    op.drop_column('board_like', 'user_id')
    # ### end Alembic commands ###
