"""empty message

Revision ID: 57146eb10d42
Revises: bb7b3035c689
Create Date: 2021-02-24 17:29:54.603359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57146eb10d42'
down_revision = 'bb7b3035c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('order_total_price', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('way_of_payment', sa.String(length=50), nullable=True),
    sa.Column('order_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_order_id', sa.Integer(), nullable=True),
    sa.Column('menus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_order_id'], ['main_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menus_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_data')
    op.drop_table('cart')
    op.drop_table('main_order')
    op.drop_table('option')
    # ### end Alembic commands ###
