"""empty message

Revision ID: 5ee644b9319e
Revises: 2543d331efd7
Create Date: 2021-02-28 11:43:41.869767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee644b9319e'
down_revision = '2543d331efd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('total_quantity', sa.Integer(), nullable=True))
    op.drop_column('main_order', 'quantity')
    op.add_column('order_detail', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_detail', 'quantity')
    op.add_column('main_order', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('main_order', 'total_quantity')
    # ### end Alembic commands ###
