"""empty message

Revision ID: 5eff2dfe149e
Revises: c31f0a19b3d2
Create Date: 2021-02-26 17:44:53.714976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eff2dfe149e'
down_revision = 'c31f0a19b3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('main_order_id_key', 'main_order', type_='unique')
    op.drop_constraint('order_detail_main_order_id_fkey', 'order_detail', type_='foreignkey')
    op.drop_column('order_detail', 'main_order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('main_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_detail_main_order_id_fkey', 'order_detail', 'main_order', ['main_order_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('main_order_id_key', 'main_order', ['id'])
    # ### end Alembic commands ###
