"""empty message

Revision ID: 60ef1d232545
Revises: 2f758bb577f5
Create Date: 2021-02-25 17:25:30.652458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ef1d232545'
down_revision = '2f758bb577f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('hot_or_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'hot_or_id')
    # ### end Alembic commands ###
