"""empty message

Revision ID: 64cad5778ce8
Revises: 1efe014ad2de
Create Date: 2021-02-24 15:04:39.013340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cad5778ce8'
down_revision = '1efe014ad2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_like_board_id_fkey', 'board_like', type_='foreignkey')
    op.drop_constraint('board_like_users_id_fkey', 'board_like', type_='foreignkey')
    op.create_foreign_key(None, 'board_like', 'board', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'board_like', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_like', type_='foreignkey')
    op.drop_constraint(None, 'board_like', type_='foreignkey')
    op.create_foreign_key('board_like_users_id_fkey', 'board_like', 'users', ['users_id'], ['id'])
    op.create_foreign_key('board_like_board_id_fkey', 'board_like', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###
