"""empty message

Revision ID: 70966c4ff783
Revises: 24569b749172
Create Date: 2021-02-26 17:41:42.448159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70966c4ff783'
down_revision = '24569b749172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('main_order_id_key', 'main_order', type_='unique')
    op.create_unique_constraint(None, 'main_order', ['uuid'])
    op.drop_column('main_order', 'id')
    op.drop_constraint('order_detail_main_order_id_fkey', 'order_detail', type_='foreignkey')
    op.drop_column('order_detail', 'main_order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('main_order_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_detail_main_order_id_fkey', 'order_detail', 'main_order', ['main_order_id'], ['id'], ondelete='CASCADE')
    op.add_column('main_order', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('main_order_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'main_order', type_='unique')
    op.create_unique_constraint('main_order_id_key', 'main_order', ['id'])
    op.drop_column('main_order', 'uuid')
    # ### end Alembic commands ###
