"""empty message

Revision ID: 71bd1d8169dd
Revises: 9e1e7ff0cc4f
Create Date: 2021-02-19 18:17:06.040777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bd1d8169dd'
down_revision = '9e1e7ff0cc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    # ### end Alembic commands ###
