"""empty message

Revision ID: 73fc8ba01074
Revises: d9442f1217e8
Create Date: 2021-02-22 13:56:35.263814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fc8ba01074'
down_revision = 'd9442f1217e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_like',
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], name='store_like_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id', name='store_like_pkey')
    )
    # ### end Alembic commands ###
