"""empty message

Revision ID: 74682e6c4d1e
Revises: 2d8c19e30e89
Create Date: 2021-02-21 00:17:20.351129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74682e6c4d1e'
down_revision = '2d8c19e30e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('comment', sa.String(length=300), nullable=False))
    op.drop_column('board', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('content', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('board', 'comment')
    # ### end Alembic commands ###
