"""empty message

Revision ID: 75186948b82e
Revises: aee6cbbc6919
Create Date: 2021-02-22 00:03:41.152257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75186948b82e'
down_revision = 'aee6cbbc6919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'board', 'store', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'store_id')
    # ### end Alembic commands ###
