"""empty message

Revision ID: 8107ff632909
Revises: a0caed96a332
Create Date: 2021-02-22 18:04:09.010558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8107ff632909'
down_revision = 'a0caed96a332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('break_day', sa.String(length=50), nullable=True))
    op.drop_column('store', 'break_dayy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('break_dayy', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('store', 'break_day')
    # ### end Alembic commands ###
