"""empty message

Revision ID: 813a6f0df99a
Revises: ac7b94893099
Create Date: 2021-02-26 11:09:10.506803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813a6f0df99a'
down_revision = 'ac7b94893099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_option_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'option_id')
    op.drop_constraint('order_data_option_id_fkey', 'order_data', type_='foreignkey')
    op.drop_column('order_data', 'option_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_data', sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_data_option_id_fkey', 'order_data', 'option', ['option_id'], ['id'])
    op.add_column('cart', sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cart_option_id_fkey', 'cart', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###
