"""empty message

Revision ID: 859340b2ebb2
Revises: 948ebd674e69
Create Date: 2021-02-26 15:56:44.194690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859340b2ebb2'
down_revision = '948ebd674e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_data', sa.Column('option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_data', 'option', ['option_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_data', type_='foreignkey')
    op.drop_column('order_data', 'option_id')
    # ### end Alembic commands ###
