"""empty message

Revision ID: 8ce431e1a7e3
Revises: 74962674b900
Create Date: 2021-03-04 16:17:00.184888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ce431e1a7e3'
down_revision = '74962674b900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_option_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_option_table',
    sa.Column('menu_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('option_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.uuid'], name='menu_option_table_menu_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.uuid'], name='menu_option_table_option_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
