"""empty message

Revision ID: 8d9dc8fc9316
Revises: 3339271197d9
Create Date: 2021-02-26 17:34:52.127880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9dc8fc9316'
down_revision = '3339271197d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'main_order', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_order', type_='unique')
    # ### end Alembic commands ###
