"""empty message

Revision ID: 8fd4c7bdbd88
Revises: 8ffa93d78d56
Create Date: 2021-02-21 00:22:49.965144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd4c7bdbd88'
down_revision = '8ffa93d78d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'comment',
               existing_type=sa.VARCHAR(length=300),
               nullable=False,
               existing_server_default=sa.text("'1'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'comment',
               existing_type=sa.VARCHAR(length=300),
               nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
    # ### end Alembic commands ###
