"""empty message

Revision ID: 8ffa93d78d56
Revises: 74682e6c4d1e
Create Date: 2021-02-21 00:21:56.935872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffa93d78d56'
down_revision = '74682e6c4d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('comment', sa.String(length=300), server_default='1', nullable=True))
    op.drop_column('board', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('content', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('board', 'comment')
    # ### end Alembic commands ###
