"""empty message

Revision ID: 90503410a402
Revises: 57c32cba4064
Create Date: 2021-02-26 15:07:53.206712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90503410a402'
down_revision = '57c32cba4064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('expect_time', sa.String(), nullable=True))
    op.add_column('main_order', sa.Column('extra_require', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_order', 'extra_require')
    op.drop_column('main_order', 'expect_time')
    # ### end Alembic commands ###
