"""empty message

Revision ID: 97fc203728d7
Revises: 763fbee93c87
Create Date: 2021-02-25 15:15:12.878909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97fc203728d7'
down_revision = '763fbee93c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('option_uuid', sa.Integer(), nullable=True))
    op.drop_constraint('cart_option_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'option', ['option_uuid'], ['uuid'])
    op.drop_column('cart', 'option_id')
    op.add_column('option', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('option_id_key', 'option', type_='unique')
    op.create_unique_constraint(None, 'option', ['uuid'])
    op.drop_column('option', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('option_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'option', type_='unique')
    op.create_unique_constraint('option_id_key', 'option', ['id'])
    op.drop_column('option', 'uuid')
    op.add_column('cart', sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_option_id_fkey', 'cart', 'option', ['option_id'], ['id'])
    op.drop_column('cart', 'option_uuid')
    # ### end Alembic commands ###
