"""empty message

Revision ID: a0caed96a332
Revises: 44e204347672
Create Date: 2021-02-22 18:03:48.184656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0caed96a332'
down_revision = '44e204347672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('break_dayy', sa.String(length=50), nullable=True))
    op.drop_column('store', 'break_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('break_day', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('store', 'break_dayy')
    # ### end Alembic commands ###
