"""empty message

Revision ID: a17372f62bfa
Revises: acd633aa8398
Create Date: 2021-02-26 11:00:39.274713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17372f62bfa'
down_revision = 'acd633aa8398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('tes', sa.Integer(), nullable=False))
    op.drop_constraint('option_menu_id_fkey', 'option', type_='foreignkey')
    op.drop_column('option', 'option_name')
    op.drop_column('option', 'extra_price')
    op.drop_column('option', 'menu_id')
    op.drop_column('option', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('option', sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('option', sa.Column('extra_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('option', sa.Column('option_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('option_menu_id_fkey', 'option', 'menus', ['menu_id'], ['id'])
    op.drop_column('option', 'tes')
    # ### end Alembic commands ###
