"""empty message

Revision ID: a7787bfcc4a4
Revises: ac4c42f37360
Create Date: 2021-02-25 16:55:30.426243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7787bfcc4a4'
down_revision = 'ac4c42f37360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_id')
    op.add_column('option', sa.Column('test_id', sa.Enum('1', '2', '3', name='myenum'), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option', 'test_id')
    op.create_table('test_id',
    sa.Column('value', postgresql.ENUM('one', 'two', 'three', name='myenum'), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
