"""empty message

Revision ID: ac4c42f37360
Revises: f43032920f9b
Create Date: 2021-02-25 16:32:02.132215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac4c42f37360'
down_revision = 'f43032920f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_id',
    sa.Column('value', sa.Enum('one', 'two', 'three', name='myenum'), nullable=True)
    )
    op.add_column('cart', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'store', ['store_id'], ['id'])
    op.add_column('order_data', sa.Column('option_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'order_data', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_data', type_='foreignkey')
    op.drop_column('order_data', 'option_id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'store_id')
    op.drop_table('test_id')
    # ### end Alembic commands ###
