"""empty message

Revision ID: ad46a7092c35
Revises: 31c6b449295b
Create Date: 2021-02-26 13:45:18.329390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad46a7092c35'
down_revision = '31c6b449295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('option_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('quantity', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(None, 'cart', 'menus', ['menu_id'], ['id'])
    op.create_foreign_key(None, 'cart', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'quantity')
    op.drop_column('cart', 'option_id')
    op.drop_column('cart', 'menu_id')
    # ### end Alembic commands ###
