"""empty message

Revision ID: aee6cbbc6919
Revises: 13384145bc0b
Create Date: 2021-02-22 00:01:48.696882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee6cbbc6919'
down_revision = '13384145bc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('store_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'board', 'store', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.drop_column('board', 'store_id')
    # ### end Alembic commands ###
