"""empty message

Revision ID: b0c272df5915
Revises: 1719a9c369bf
Create Date: 2021-02-21 20:53:18.732905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c272df5915'
down_revision = '1719a9c369bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_img', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['name'])
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_img')
    # ### end Alembic commands ###
