"""empty message

Revision ID: b3638c5d7c1f
Revises: 1be5f2a16a7f
Create Date: 2021-02-26 17:46:09.614764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3638c5d7c1f'
down_revision = '1be5f2a16a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('main_order_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'order_detail', 'main_order', ['main_order_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.drop_column('order_detail', 'main_order_id')
    # ### end Alembic commands ###
