"""empty message

Revision ID: bb5c662e9d1c
Revises: 1c7a7924bfe6
Create Date: 2021-02-23 21:46:56.205485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb5c662e9d1c'
down_revision = '1c7a7924bfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_follow_list')
    op.alter_column('board', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('users_follow_list',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follow_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follow_user_id'], ['users.id'], name='users_follow_list_follow_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_follow_list_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'follow_user_id', name='users_follow_list_pkey')
    )
    # ### end Alembic commands ###
