"""empty message

Revision ID: c31f0a19b3d2
Revises: 70966c4ff783
Create Date: 2021-02-26 17:44:00.300935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c31f0a19b3d2'
down_revision = '70966c4ff783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('main_order_id_key', 'main_order', type_='unique')
    op.create_unique_constraint(None, 'main_order', ['uuid'])
    op.drop_column('main_order', 'id')
    op.drop_constraint('order_detail_main_order_id_fkey', 'order_detail', type_='foreignkey')
    op.create_foreign_key(None, 'order_detail', 'main_order', ['main_order_id'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_detail', type_='foreignkey')
    op.create_foreign_key('order_detail_main_order_id_fkey', 'order_detail', 'main_order', ['main_order_id'], ['id'], ondelete='CASCADE')
    op.add_column('main_order', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('main_order_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'main_order', type_='unique')
    op.create_unique_constraint('main_order_id_key', 'main_order', ['id'])
    op.drop_column('main_order', 'uuid')
    # ### end Alembic commands ###
