"""empty message

Revision ID: cb78960bde1e
Revises: 9abce378b63a
Create Date: 2021-02-21 12:21:07.096325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb78960bde1e'
down_revision = '9abce378b63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
