"""empty message

Revision ID: cbbcb40ca5f2
Revises: d01f8834c700
Create Date: 2021-03-03 14:23:01.901762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbbcb40ca5f2'
down_revision = 'd01f8834c700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('js_order_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_order', 'js_order_data')
    # ### end Alembic commands ###
