"""empty message

Revision ID: ce0b2a352114
Revises: 56133b78d9e9
Create Date: 2021-02-22 15:44:22.676398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b2a352114'
down_revision = '56133b78d9e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('image', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'image')
    # ### end Alembic commands ###
