"""empty message

Revision ID: d01f8834c700
Revises: 48dd0ece0bbe
Create Date: 2021-03-02 14:39:25.551378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01f8834c700'
down_revision = '48dd0ece0bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('create_att', sa.DateTime(), nullable=True))
    op.drop_column('store', 'create_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('create_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('store', 'create_att')
    # ### end Alembic commands ###
