"""empty message

Revision ID: d053af454bc7
Revises: cb78960bde1e
Create Date: 2021-02-21 12:22:21.717357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd053af454bc7'
down_revision = 'cb78960bde1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'content',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
