"""empty message

Revision ID: d224e1ae646a
Revises: a17372f62bfa
Create Date: 2021-02-26 11:02:20.451887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd224e1ae646a'
down_revision = 'a17372f62bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('extra_price', sa.Integer(), nullable=True))
    op.add_column('option', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('option', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.add_column('option', sa.Column('option_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'option', 'menus', ['menu_id'], ['id'])
    op.drop_column('option', 'tes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('tes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.drop_column('option', 'option_name')
    op.drop_column('option', 'menu_id')
    op.drop_column('option', 'id')
    op.drop_column('option', 'extra_price')
    # ### end Alembic commands ###
