"""empty message

Revision ID: dccbf7bd5a33
Revises: 223504ef7fe6
Create Date: 2021-02-24 15:18:04.184024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccbf7bd5a33'
down_revision = '223504ef7fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_like', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('board_like', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_like', 'users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('board_like', 'board_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
