"""empty message

Revision ID: e024341f7c00
Revises: 52f92adbe268
Create Date: 2021-03-02 10:30:37.735709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e024341f7c00'
down_revision = '52f92adbe268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_store_id_fkey', 'option', type_='foreignkey')
    op.create_foreign_key(None, 'option', 'store', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'option', type_='foreignkey')
    op.create_foreign_key('option_store_id_fkey', 'option', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###
