"""empty message

Revision ID: e9a421074946
Revises: 5ee644b9319e
Create Date: 2021-02-28 11:49:32.683198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a421074946'
down_revision = '5ee644b9319e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('main_order_user_ide_fkey', 'main_order', type_='foreignkey')
    op.create_foreign_key(None, 'main_order', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('main_order', 'user_ide')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_order', sa.Column('user_ide', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'main_order', type_='foreignkey')
    op.create_foreign_key('main_order_user_ide_fkey', 'main_order', 'users', ['user_ide'], ['id'], ondelete='CASCADE')
    op.drop_column('main_order', 'user_id')
    # ### end Alembic commands ###
