"""empty message

Revision ID: eceb1dbebf43
Revises: 6493caf1cac1
Create Date: 2021-02-25 15:22:51.980900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eceb1dbebf43'
down_revision = '6493caf1cac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('option_uuid_key', 'option', type_='unique')
    op.create_unique_constraint(None, 'option', ['id'])
    op.drop_column('option', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'option', type_='unique')
    op.create_unique_constraint('option_uuid_key', 'option', ['uuid'])
    op.drop_column('option', 'id')
    # ### end Alembic commands ###
