"""empty message

Revision ID: eeac80bfa2b6
Revises: 11eb357422d4
Create Date: 2021-02-26 11:51:21.736954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeac80bfa2b6'
down_revision = '11eb357422d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###
