"""empty message

Revision ID: f0553055973e
Revises: 2193e12dec7f
Create Date: 2021-02-26 10:29:58.383384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0553055973e'
down_revision = '2193e12dec7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('option_id_key', 'option', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('option_id_key', 'option', ['id'])
    # ### end Alembic commands ###
