"""empty message

Revision ID: f34457040caf
Revises: 4220b7088b14
Create Date: 2021-03-01 19:47:33.911725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34457040caf'
down_revision = '4220b7088b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_option_table',
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], ondelete='CASCADE')
    )
    op.create_unique_constraint(None, 'refresh', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh', type_='unique')
    op.drop_table('menu_option_table')
    # ### end Alembic commands ###
