"""empty message

Revision ID: f43032920f9b
Revises: 11090f350c03
Create Date: 2021-02-25 16:28:54.218855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f43032920f9b'
down_revision = '11090f350c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'store', ['store_id'], ['id'])
    op.add_column('option', sa.Column('test_id', sa.Enum('one', 'two', 'three', name='myenum'), nullable=True))
    op.add_column('order_data', sa.Column('option_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'order_data', 'option', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_data', type_='foreignkey')
    op.drop_column('order_data', 'option_id')
    op.drop_column('option', 'test_id')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'store_id')
    # ### end Alembic commands ###
